version: "3.9"
services:
  db:
    image: postgres:16
    container_name: nodeapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-nodeapi}
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-postgres} -d ${PGDATABASE:-nodeapi}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: nodeapi-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@db:5432/${PGDATABASE:-nodeapi}?schema=public
      UPLOAD_DIR: /var/app/uploads/items
    volumes:
      - uploads:/var/app/uploads
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    profiles: ["api"]   # <- optional, not started by default

volumes:
  pgdata:
  uploads:
